### ISSUE TITLE
CI is failing due to https://github.com/homalg-project/CAP_project/pull/1054

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/InternalModules#27]
@mohamed-barakat

**Comment by zickgraf** [comment]
bump

**Comment by mohamed-barakat** [comment]
What is missing are the equalizers and the coequalizers.

**Comment by zickgraf** [comment]
> What is missing are the equalizers and the coequalizers.

You mean for the category to be IsFiniteCompleteCategory and IsFiniteCocompleteCategory algorithmically? Yes, but for the CI to succeed simply the notebooks have to be updated.

**Comment by mohamed-barakat** [comment]
Yes, I have to update them again once Equalizers and Coequalizers are added, because the difference will vanish :)

**Comment by zickgraf** [comment]
> Yes, I have to update them again once Equalizers and Coequalizers are added, because the difference will vanish :)

Even if equalizers and coequalizers had already been added, the CI would still produce a difference because also `IsSkeletalCategory` is listed now. That's why I was confused by your statement about "missing equalizers and coequalizers" above.
